import Providers from '@/components/providers'
import './globals.css'
import { ConnectWallet } from '@/components/connect-wallet'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <header>
            <ConnectWallet />
          </header>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
